### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by amio** [amio/eb#8]
一些基本原则
- 版本号采用 SemVer 规则
- 从 1.0 开始打版本号。1.0 之前的开发内容不做版本发布
- 开发初期 Issue、PullRequest 可以随意采用中英文。沟通高效优先。
### MILESTONE v1.0

**实现服务稳定运行**
- [x] 整理目录结构，命名规则。目标是方便开发、部署和随时更新
- [x] 把 nedb 换个性能更好的数据库（选项：~~Redis~~ / RethinkDB / MongoDB）
- [ ] 服务器端 API 改进（排序、分页）
  - [x] URL 规则
  - [x] 客户端传参到服务端的方式
  - [ ] 服务端支持查询参数
- [x] 实现初步账号控制
  - [x] 百姓超人账号访问许可
- [x] 通知系统
  - [x] 错误超过指定的阀值会发出通知邮件
- [x] 修正所有可见报错
- [ ] README文档更新
  - [ ] 完善安装部署说明
### MILESTONE v1.1

**（对1.0的第一个维护版本）**
- 支持查看原始数据
  - [ ] 查询规则、界面和交互设计
  - [ ] 前后端实现
- 性能评估
  - [ ] 支持的并发数、CPU和内存占用
  - [ ] 估计出可以承受的压力上限
  - [ ] 过载的应对方案
- 界面优化
  - [ ] 图标改为 Icon Font。包括内联 SVG，浏览器的PNG Icon。
  - [ ] 修整文案
### MILESTONE v1.x

**（预计内容）**
- 筛选（如过滤掉某些数据，看其他排名等等，以 Reids 天然支持的特性为优选）
  - 客户端配置规则
  - 服务端 API 支持
- 完善账号系统
  - [ ] 更多开放登陆方案（OAuth2）
  - （可能）基于账号的设置项
- 通知系统
  - 基于账号系统 + 筛选机制的报警机制（Error 信息到达一定阀值时发出邮件通知）
- Dashboard 重构
  - 更多图标、更实用的实时监控（适用于大屏幕的版本）

**Comment by amio** [comment]
@hax 之前订的计划内容，可能实施的优先级顺序需要调整下了
